#!/bin/sh

if [[ $(git status -s) ]]
then
    echo "The working directory is dirty. Please commit any pending changes."
    exit 1;
fi

echo "Checkout to demo page branch"
git co gh-pages

echo "Updating files"
git show master:public/index.html > index.html
git show master:public/images/favico.png > ./images/favico.png
git show master:public/javascript/clappr-config.js > ./javascript/clappr-config.js
rm -rf node_modules

echo "Publishing"
git add . && git commit -m "Update demo page" && git push origin gh-pages && git co master

echo "Done!"
